#!/usr/bin/env bash
# This script displays To infinity and beyond and handles SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2 &
    wait
#!/usr/bin/env bash
# This script displays a message when it receives a SIGTERM signal

# The trap command: 
# It catches SIGTERM and then executes the echo command
trap "echo 'I am invincible!!!'" SIGTERM

# We need a loop to keep the process running so it can actually receive the signal
while true; do
    sleep 1
done
